services:
  carlemany-backend:
    build:
      context: .
      target: carlemany-backend-base
    image: carlemany-backend-base:latest
    volumes:
      - type: bind
        source: .
        target: /carlemany-backend
    ports:
      - "8000:80"
    networks:
      - carlemany-net
    depends_on:
      - db
      - migrate
    env_file:
      - .env

  black:
    image: carlemany-backend-base:latest
    profiles: ["devtools"]
    volumes:
      - type: bind
        source: ./
        target: /carlemany-backend
        read_only: true
    entrypoint: sh -c "black --config .black --check --diff ."

  test: &test
    build: .
    image: carlemany-backend-dev:latest
    profiles: ["devtools"]
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./
        target: /carlemany-backend
    networks:
      - carlemany-net
    entrypoint: pytest --maxfail=10

  test-cov:
    <<: *test
    profiles: ["devtools"]
    entrypoint: pytest --maxfail=10 --cov --cov-report=term --cov-report=html --junitxml=tests/test-results/junit.xml

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${SQL_DB_USER}
      POSTGRES_PASSWORD: ${SQL_DB_PASSWORD}
      POSTGRES_DB: ${SQL_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - carlemany-net

  migrate:
    build: .
    depends_on:
      - db
    environment:
      SQL_DB_USER: ${SQL_DB_USER}
      SQL_DB_PASSWORD: ${SQL_DB_PASSWORD}
      SQL_DB_HOST: ${SQL_DB_HOST}
      SQL_DB_PORT: ${SQL_DB_PORT}
      SQL_DB_NAME: ${SQL_DB_NAME}
    networks:
      - carlemany-net
    entrypoint: aerich upgrade

  make_migrations:
    build: .
    profiles: ["devtools"]
    depends_on:
      - db
    environment:
      SQL_DB_USER: ${SQL_DB_USER}
      SQL_DB_PASSWORD: ${SQL_DB_PASSWORD}
      SQL_DB_HOST: ${SQL_DB_HOST}
      SQL_DB_PORT: ${SQL_DB_PORT}
      SQL_DB_NAME: ${SQL_DB_NAME}
    networks:
      - carlemany-net
    entrypoint: aerich migrate

networks:
  carlemany-net:

volumes:
  postgres_data: